### ISSUE TITLE
Sorting and shuffling can happen at the same time

### ISSUE THREAD

**Issue by brookr** [jonathanstallings/getSorted#2]
Great looking page! Very nicely visualized.

Minor bug to report:

Shuffling and sorting can be triggered while the other is already running. That leads to some trippy swapping! 

Maybe disable ALL buttons (you can add an attribute of `disabled="disabled"` to a button) if any one algo is running?

Again, nicely done on the whole!

**Comment by jonathanstallings** [comment]
Oh my! Trippy indeed! Thanks for the catch.

**Comment by jonathanstallings** [comment]
Control buttons now disabled during ongoing animation. Later I should probably look into queuing animation in another way so that I have more options stopping it early, if needed.

Thanks again.

**Comment by brookr** [comment]
:+1: !!
